#ifndef BOOT_ERR_H
#define BOOT_ERR_H

#define BOOT_ERR_NO_ERROR 0
#define BOOT_ERR_INVALID_PARAM -1
#define BOOT_ERR_FLASH_INIT_FAILED -2
#define BOOT_ERR_FLASH_READ_FAILED -3
#define BOOT_ERR_FLASH_WRITE_FAILED -4
#define BOOT_ERR_FLASH_ERASE_FAILED -5
#define BOOT_ERR_JUMP_TO_APPLICATION_FAILED -7
#define BOOT_PARTITION_MGIC_NUMBER_MISMATCH -8
#define BOOT_ERR_UNKNOWN -99

#endif // BOOT_ERR_H