#ifndef FLASH_DEFINE_H
#define FLASH_DEFINE_H

#define SECONDARY_FLASH 1
#define FACTORY_APP_FLASH 1
#define SCRATCH_FLASH 1

#define FLASH_NUMBER_OF_SECTORS 256

#define BOOT_FLASH_SECTOR_SIZE 0x2000 // 8KB sector size for STM32H5 series

#define BOOTLOADER_FLASH_START_ADDRESS 0x08000000
#define BOOTLOADER_FLASH_NUMBER_OF_SECTORS 7
#define BOOTLOADER_FLASH_SIZE (BOOTLOADER_FLASH_NUMBER_OF_SECTORS * BOOT_FLASH_SECTOR_SIZE)

#define PARTITION_FLASH_START_ADDRESS (BOOTLOADER_FLASH_START_ADDRESS + BOOTLOADER_FLASH_SIZE)
#define PARTITION_FLASH_NUMBER_OF_SECTORS 1
#define PARTITION_FLASH_SIZE BOOT_FLASH_SECTOR_SIZE // 8KB partition size for STM32H5 series

#define PRIMARY_APP_FLASH_START_ADDRESS (PARTITION_FLASH_START_ADDRESS + PARTITION_FLASH_SIZE)
#define PRIMARY_APP_FLASH_NUMBER_OF_SECTORS 60
#define PRIMARY_APP_FLASH_SIZE (PRIMARY_APP_FLASH_NUMBER_OF_SECTORS * BOOT_FLASH_SECTOR_SIZE)

#define SECONDARY_APP_FLASH_START_ADDRESS (PRIMARY_APP_FLASH_START_ADDRESS + PRIMARY_APP_FLASH_SIZE)
#define SECONDARY_APP_FLASH_NUMBER_OF_SECTORS 60
#define SECONDARY_APP_FLASH_SIZE (SECONDARY_APP_FLASH_NUMBER_OF_SECTORS * BOOT_FLASH_SECTOR_SIZE)

#define FACTORY_APP_FLASH_START_ADDRESS (SECONDARY_APP_FLASH_START_ADDRESS + SECONDARY_APP_FLASH_SIZE)
#define FACTORY_APP_FLASH_NUMBER_OF_SECTORS 60
#define FACTORY_APP_FLASH_SIZE (FACTORY_APP_FLASH_NUMBER_OF_SECTORS * BOOT_FLASH_SECTOR_SIZE)

#define SCRATCH_FLASH_START_ADDRESS (FACTORY_APP_FLASH_START_ADDRESS + FACTORY_APP_FLASH_SIZE)
#define SCRATCH_FLASH_NUMBER_OF_SECTORS 1
#define SCRATCH_FLASH_SIZE (SCRATCH_FLASH_NUMBER_OF_SECTORS * BOOT_FLASH_SECTOR_SIZE)

#define BOOT_MCU_C0 0
#define BOOT_MCU_C5 1
#define BOOT_MCU_G0 2
#define BOOT_MCU_F0 3
#define BOOT_MCU_F1 4
#define BOOT_MCU_F2 5
#define BOOT_MCU_F3 6
#define BOOT_MCU_F4 7
#define BOOT_MCU_F7 8
#define BOOT_MCU_H5 9
#define BOOT_MCU_H7 10
#define BOOT_MCU_L0 11
#define BOOT_MCU_L4 12
#define BOOT_MCU_L5 13
#define BOOT_MCU_U3 14
#define BOOT_MCU_U5 15

// #define CFG_BOOT_MCU BOOT_MCU_H5

#endif // FLASH_DEFINE_H