#ifndef MAGIC_FLASH_H
#define MAGIC_FLASH_H

#define BOOT_MAGIC_UPDATE               0xABCD0001UL
#define BOOT_MAGIC_ROLLBACK_PREV        0xABCD0002UL
#define BOOT_MAGIC_ROLLBACK_FACTORY     0xABCD0003UL
#define BOOT_MAGIC_UPDATE_FACTORY       0xABCD0004UL

#endif