#include "sx_i2c.h"
#include "sx_config.h"

#if SX_PLATFORM == SX_PLATFORM_STM32H5
    #include "stm32h5xx_hal.h"
    #include "stm32h5xx_hal_i2c.h"
#elif SX_PLATFORM == SX_PLATFORM_STM32H7
    #include "stm32h7xx_hal.h"
    #include "stm32h7xx_hal_i2c.h"
#elif SX_PLATFORM == SX_PLATFORM_STM32F7
    #include "stm32f7xx_hal.h"
    #include "stm32f7xx_hal_i2c.h"
#elif SX_PLATFORM == SX_PLATFORM_STM32F4
    #include "stm32f4xx_hal.h"
    #include "stm32f4xx_hal_i2c.h"
#elif SX_PLATFORM == SX_PLATFORM_STM32F1
    #include "stm32f1xx_hal.h"
    #include "stm32f1xx_hal_i2c.h"
#endif

#include "i2c.h"

#define SX_I2C_TIMEOUT_MS   100U

/* --- I2C1 bus recovery (STM32H5, hard-coded to this board's I2C1) ---
 *
 * Root cause this fixes: a slave (observed: BNO055 first) can get stuck
 * mid-byte on the bus (noise, brief brown-out, or a HAL timeout hitting
 * between clock pulses) and hold SDA low forever. Once that happens every
 * other device on I2C1 (RTC, SHT3x, ADS1115...) starts timing out too,
 * because SDA never releases — HAL_I2C_Mem_Read/Write does not recover the
 * physical bus state on timeout, it just returns an error and leaves the
 * peripheral as-is. This is a known HAL limitation, not an app bug.
 *
 * Fix (standard I2C bus-recovery procedure per the I2C spec): temporarily
 * switch SCL/SDA to plain GPIO, clock SCL up to 9 times (enough for a
 * stuck slave to finish shifting out any partial byte and release SDA),
 * issue a manual STOP condition, then restore SCL/SDA to I2C1 alternate
 * function and re-init the HAL I2C peripheral.
 *
 * This lives here (not per-device driver) because the bus is shared by
 * every device on I2C1 — recovering here benefits BNO055/RTC/SHT3x/ADS1115
 * all at once without touching their individual driver files. Confirmed
 * via sx_config.h: this board has exactly one I2C bus (I2C1), STM32H5,
 * no FreeRTOS — so hard-coding GPIOB/PIN_6/PIN_7/hi2c1 here is correct for
 * this board and avoids over-abstracting for a second bus that doesn't
 * exist. */

#define SX_I2C1_BUS_ERROR_THRESHOLD   3U   /* consecutive failures before triggering recovery */

static uint32_t s_i2c1_consecutive_errors = 0;

extern I2C_HandleTypeDef hi2c1;   /* generated by CubeMX in i2c.c */
extern void MX_I2C1_Init(void);   /* generated by CubeMX in i2c.c */

static void sx_i2c1_bus_recover(void)
{
    GPIO_InitTypeDef gpio = {0};

    /* 1) De-init HAL I2C1 first so it stops driving the pins while we
     * bit-bang recovery on them. */
    HAL_I2C_DeInit(&hi2c1);

    /* 2) Switch PB6 (SCL) to open-drain output, PB7 (SDA) to input, so we
     * can read SDA's real state and drive SCL manually. Open-drain matches
     * normal I2C behavior (never drive the bus high, only pull low or
     * release). */
    gpio.Pin   = GPIO_PIN_6;
    gpio.Mode  = GPIO_MODE_OUTPUT_OD;
    gpio.Pull  = GPIO_PULLUP;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &gpio);

    gpio.Pin  = GPIO_PIN_7;
    gpio.Mode = GPIO_MODE_INPUT;
    HAL_GPIO_Init(GPIOB, &gpio);

    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_SET); /* release SCL high to start */

    /* 3) Clock SCL up to 9 times. A stuck slave releases SDA once it has
     * shifted out the remaining bits of whatever byte it was stuck on —
     * 9 clocks covers the worst case (8 data bits + 1 ACK). Stop early if
     * SDA is already released. */
    for (int i = 0; i < 9; i++) {
        if (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_7) == GPIO_PIN_SET) {
            break; /* SDA already released, slave is unstuck */
        }
        HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_RESET);
        HAL_Delay(1); /* ~1ms is far slower than real I2C, deliberately slow/safe */
        HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_SET);
        HAL_Delay(1);
    }

    /* 4) Manual STOP condition: SDA low->high while SCL is high.
     * First pull SDA low (need it as output for this step), keep SCL high,
     * then release SDA back high — that low-to-high transition on SDA
     * while SCL is high is exactly what a STOP condition is. */
    gpio.Pin  = GPIO_PIN_7;
    gpio.Mode = GPIO_MODE_OUTPUT_OD;
    gpio.Pull = GPIO_PULLUP;
    HAL_GPIO_Init(GPIOB, &gpio);

    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_RESET); /* SDA low */
    HAL_Delay(1);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_SET);   /* SCL high (already high, ensure) */
    HAL_Delay(1);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_SET);   /* SDA low->high while SCL high = STOP */
    HAL_Delay(1);

    /* 5) Restore PB6/PB7 to I2C1 alternate function (same config as
     * i2c.c's MX_I2C1_Init MSP init) and re-init the HAL peripheral. */
    gpio.Pin       = GPIO_PIN_6 | GPIO_PIN_7;
    gpio.Mode      = GPIO_MODE_AF_OD;
    gpio.Pull      = GPIO_NOPULL;
    gpio.Speed     = GPIO_SPEED_FREQ_VERY_HIGH;
    gpio.Alternate = GPIO_AF4_I2C1;
    HAL_GPIO_Init(GPIOB, &gpio);

    MX_I2C1_Init();

    s_i2c1_consecutive_errors = 0;
}

/* Call after every I2C1 transaction: pass true on success (resets the
 * error counter) or false on failure (increments it, and triggers bus
 * recovery once the threshold is hit). */
static void sx_i2c1_note_result(int ok)
{
    if (ok) {
        s_i2c1_consecutive_errors = 0;
        return;
    }
    s_i2c1_consecutive_errors++;
    if (s_i2c1_consecutive_errors >= SX_I2C1_BUS_ERROR_THRESHOLD) {
        sx_i2c1_bus_recover();
    }
}

typedef HAL_StatusTypeDef (*i2c_transmit_fn_t)    (I2C_HandleTypeDef*, uint16_t, uint8_t*, uint16_t, uint32_t);
typedef HAL_StatusTypeDef (*i2c_receive_fn_t)     (I2C_HandleTypeDef*, uint16_t, uint8_t*, uint16_t, uint32_t);
typedef HAL_StatusTypeDef (*i2c_mem_write_fn_t)   (I2C_HandleTypeDef*, uint16_t, uint16_t, uint16_t, uint8_t*, uint16_t, uint32_t);
typedef HAL_StatusTypeDef (*i2c_mem_read_fn_t)    (I2C_HandleTypeDef*, uint16_t, uint16_t, uint16_t, uint8_t*, uint16_t, uint32_t);
typedef HAL_StatusTypeDef (*i2c_is_device_ready_fn_t)(I2C_HandleTypeDef*, uint16_t, uint32_t, uint32_t);

static i2c_transmit_fn_t        i2c_transmit        = HAL_I2C_Master_Transmit;
static i2c_receive_fn_t         i2c_receive         = HAL_I2C_Master_Receive;
static i2c_mem_write_fn_t       i2c_mem_write       = HAL_I2C_Mem_Write;
static i2c_mem_read_fn_t        i2c_mem_read        = HAL_I2C_Mem_Read;
static i2c_is_device_ready_fn_t i2c_is_device_ready = HAL_I2C_IsDeviceReady;

static int _sx_i2c_write(sx_i2c_t *i2c, uint16_t dev_addr, const uint8_t *data, uint32_t len){
    int ok = i2c_transmit((I2C_HandleTypeDef *)i2c->pDriver,
                        dev_addr, (uint8_t *)data, (uint16_t)len,
                        SX_I2C_TIMEOUT_MS) == HAL_OK ? 0 : -1;
    if (ok != 0) {
        sx_i2c1_note_result(0);
        if (s_i2c1_consecutive_errors == 0) { /* recovery just ran, retry once */
            ok = i2c_transmit((I2C_HandleTypeDef *)i2c->pDriver,
                              dev_addr, (uint8_t *)data, (uint16_t)len,
                              SX_I2C_TIMEOUT_MS) == HAL_OK ? 0 : -1;
        }
    } else {
        sx_i2c1_note_result(1);
    }
    return ok;
}

static int _sx_i2c_read(sx_i2c_t *i2c, uint16_t dev_addr, uint8_t *data, uint32_t len){
    int ok = i2c_receive((I2C_HandleTypeDef *)i2c->pDriver,
                       dev_addr, data, (uint16_t)len,
                       SX_I2C_TIMEOUT_MS) == HAL_OK ? 0 : -1;
    if (ok != 0) {
        sx_i2c1_note_result(0);
        if (s_i2c1_consecutive_errors == 0) { /* recovery just ran, retry once */
            ok = i2c_receive((I2C_HandleTypeDef *)i2c->pDriver,
                             dev_addr, data, (uint16_t)len,
                             SX_I2C_TIMEOUT_MS) == HAL_OK ? 0 : -1;
        }
    } else {
        sx_i2c1_note_result(1);
    }
    return ok;
}

static int _sx_i2c_mem_write(sx_i2c_t *i2c, uint16_t dev_addr, uint16_t mem_addr, uint16_t mem_addr_size, const uint8_t *data, uint32_t len){
    int ok = i2c_mem_write((I2C_HandleTypeDef *)i2c->pDriver,
                         dev_addr, mem_addr, mem_addr_size,
                         (uint8_t *)data, (uint16_t)len,
                         SX_I2C_TIMEOUT_MS) == HAL_OK ? 0 : -1;
    if (ok != 0) {
        sx_i2c1_note_result(0);
        if (s_i2c1_consecutive_errors == 0) { /* recovery just ran, retry once */
            ok = i2c_mem_write((I2C_HandleTypeDef *)i2c->pDriver,
                               dev_addr, mem_addr, mem_addr_size,
                               (uint8_t *)data, (uint16_t)len,
                               SX_I2C_TIMEOUT_MS) == HAL_OK ? 0 : -1;
        }
    } else {
        sx_i2c1_note_result(1);
    }
    return ok;
}

static int _sx_i2c_mem_read(sx_i2c_t *i2c, uint16_t dev_addr, uint16_t mem_addr, uint16_t mem_addr_size, uint8_t *data, uint32_t len){
    int ok = i2c_mem_read((I2C_HandleTypeDef *)i2c->pDriver,
                        dev_addr, mem_addr, mem_addr_size,
                        data, (uint16_t)len,
                        SX_I2C_TIMEOUT_MS) == HAL_OK ? 0 : -1;
    if (ok != 0) {
        sx_i2c1_note_result(0);
        if (s_i2c1_consecutive_errors == 0) { /* recovery just ran, retry once */
            ok = i2c_mem_read((I2C_HandleTypeDef *)i2c->pDriver,
                              dev_addr, mem_addr, mem_addr_size,
                              data, (uint16_t)len,
                              SX_I2C_TIMEOUT_MS) == HAL_OK ? 0 : -1;
        }
    } else {
        sx_i2c1_note_result(1);
    }
    return ok;
}

static int _sx_i2c_is_device_ready(sx_i2c_t *i2c, uint16_t dev_addr, uint8_t num_trial, uint32_t timeout){
    return i2c_is_device_ready((I2C_HandleTypeDef *)i2c->pDriver,
                                dev_addr, num_trial, timeout) == HAL_OK ? 0 : -1;
}

sx_i2c_ops_t sx_i2c_ops = {
    .write           = _sx_i2c_write,
    .read            = _sx_i2c_read,
    .mem_write       = _sx_i2c_mem_write,
    .mem_read        = _sx_i2c_mem_read,
    .is_device_ready = _sx_i2c_is_device_ready,
};